# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Mod Properties
mod_id=extremerisinglava
mod_name=Extreme Rising Lava
mod_license=MIT
mod_version=1.2.1
mod_group_id=com.extremerisinglava
mod_authors=alexcuadroo

# NeoForge / Minecraft
minecraft_version=1.21.8
minecraft_version_range=[1.21.1,1.22)
neo_version=21.8.40
neo_version_range=[21.8.40,)
loader_version_range=[4,)

